apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mychart-debug
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  release_name: {{ .Release.Name }}
  release_namespace: {{ .Release.Namespace }}
  release_revision: {{ .Release.Revision | quote }}
  image_full: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  service_type: {{ .Values.service.type | upper }}
  replica_count: {{ .Values.replicaCount | int }}
